baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "DC43 Documentation"
theme = "docdock"
# themesdir = "../.."
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false

canonifyURLs = true
relativeURLs = true

[params]
isLatestVersion = true

showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true
googleAnalytics = "GTM-P8VJ87"

# Content variables
company_name = "IILS mbH"
product_name = "DC43"
docker_install_command_prefix = "sudo docker run --name cfy_manager_local -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN -p 80:80 -p 8000:8000"
version = "1.0.0"

[markup]
defaultMarkdownHandler = "blackfriday"
[markup.asciidocext]
    #extensions = ["asciidoctor-diagram"]
    workingFolderCurrent = true
    trace = true
    [markup.asciidocext.attributes]
        "docinfo" = "shared"
        "nofooter" = ""
        "skip-front-matter" = ""
        "library" = "asciidoctor-ruby"
        "icons" = "font"
        "sectlinks" = ""
        "sectanchors" = ""
        "figure-caption!" = ""
        "source-highlighter" = "highlightjs"
        "experimental" = "true"
        "toc-title!" = ""
        "plantuml-format" = "svg" # https://github.com/asciidoctor/asciidoctor-diagram/commit/642f17283834405088d6784e95d8b8dac62c17dc
        "ditaa-format" = "svg"
        "diagram-svg-type" = "inline"
#        "imagesoutdir" = ".asciidoctor"
#        "imagesdir" = ".asciidoctor"
        "allow-uri-read" = "" # Enable inclusion of links

[blackfriday]
hrefTargetBlank = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fa fa-phone-square'></i> <label>Support</label>"
url = "https://iils.de/contact"
weight = 60

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
url = "https://iils.de/dc43/download"
weight = 70

[[menu.shortcuts]]
name = "<i class='fa fa-paper-plane'></i> <label>Feedback</label>"
url = "mailto:docs@iils.de?subject=DC43 Documentation Feedback"
weight = 80
